Update

diff --git a/common/.local/bin/ip_of b/common/.local/bin/ip_of
--- a/common/.local/bin/ip_of
+++ b/common/.local/bin/ip_of
@@ -1,14 +1,12 @@
 #!/bin/bash
 
-MACHINE=$(get_machine)
-
-result=$(dig $1 +short)
+result=$(dig "$1" +short)
 if [ -z "$result" ]; then
-    if [[ "$MACHINE" = "Linux" ]]; then
-        result=$(avahi-browse -d local _ssh._tcp --resolve -t -p | grep $1 | awk --field-separator=";" '{print $8}')
-    else
-        echo "Error: Dig command didn't work to retrieve the ip address"
-        exit 1
-    fi
+    result=$(avahi-browse -d local _ssh._tcp --resolve -t -p | grep "$1" | awk --field-separator=";" '{print $8}')
 fi
-echo $result
+
+if [ -z "$result" ]; then
+    echo "Error: Could not resolve ip address for '$1'" >&2
+    exit 1
+fi
+echo "$result"
